version: "3.8"
services:
  react-app:
    build:
      context: ./react_frontend
      dockerfile: Dockerfile.prod
    volumes:
      - ./react_frontend/build:/app/build
  flask_proxy:
    build:
      context: ./flask_proxy
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    volumes:
      - ./react_frontend/build:/app/build:ro
  flask_user_api:
    build:
      context: ./flask_user_api
      dockerfile: Dockerfile.prod
  flask_sentiment_api:
    build:
      context: ./flask_sentiment_api
      dockerfile: Dockerfile.prod
  node_server:
    build:
      context: ./node_server
      dockerfile: Dockerfile.prod
    volumes:
      - ./node_server/server.js:/app/server.js
  mongo:
    image: mongo
    volumes:
      - ./database:/data/db
    command: mongod --quiet --logpath /dev/null 