version: "3.8"
services:
  react-app:
    build:
      context: ./react_frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./react_frontend/src:/app/src
  flask_proxy:
    build:
      context: ./flask_proxy
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./flask_proxy:/app
  flask_user_api:
    build:
      context: ./flask_user_api
      dockerfile: Dockerfile.dev
    volumes:
      - ./flask_user_api:/app
  flask_sentiment_api:
    build:
      context: ./flask_sentiment_api
      dockerfile: Dockerfile.dev
    volumes:
      - ./flask_sentiment_api:/app
  node_server:
    build:
      context: ./node_server
      dockerfile: Dockerfile.dev
    volumes:
      - ./node_server/server.js:/app/server.js
  mongo:
    image: mongo
    command: mongod --quiet --logpath /dev/null 