from flask import Flask, request 
from flask_cors import CORS
import grpc
import account_pb2 #Both files generated by grpciotools
import account_pb2_grpc 

channel = grpc.insecure_channel('node_server:50051')
stub = account_pb2_grpc.AccountServiceStub(channel)
app = Flask(__name__)
CORS(app)

@app.route('/register',methods=['POST'])
def register_api():
    data = request.get_json()
    print("Register request for username: " + data['username'])
    register_request = account_pb2.RegisterRequest(username=data['username'], password=data['password'])
    response = stub.PostRegister(register_request).response
    if(response == "Success"):
        return response, 201
    else:
        return response, 409

@app.route('/login',methods=['POST'])
def login_api():
    data = request.get_json()
    print("Login request for username: " + data['username'])
    login_request = account_pb2.LoginRequest(username=data['username'], password=data['password'])
    response = stub.PostLogin(login_request).response
    if(response == "Success"):
        return response, 202
    else:
        return response, 401

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=6000)


