# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raccount.proto\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\nLoginReply\x12\x10\n\x08response\x18\x01 \x01(\t\"5\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"!\n\rRegisterReply\x12\x10\n\x08response\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2k\n\x0e\x41\x63\x63ountService\x12\'\n\tPostLogin\x12\r.LoginRequest\x1a\x0b.LoginReply\x12\x30\n\x0cPostRegister\x12\x10.RegisterRequest\x1a\x0e.RegisterReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGINREQUEST._serialized_start=17
  _LOGINREQUEST._serialized_end=67
  _LOGINREPLY._serialized_start=69
  _LOGINREPLY._serialized_end=99
  _REGISTERREQUEST._serialized_start=101
  _REGISTERREQUEST._serialized_end=154
  _REGISTERREPLY._serialized_start=156
  _REGISTERREPLY._serialized_end=189
  _EMPTY._serialized_start=191
  _EMPTY._serialized_end=198
  _ACCOUNTSERVICE._serialized_start=200
  _ACCOUNTSERVICE._serialized_end=307
# @@protoc_insertion_point(module_scope)
